name: imgcmp
on:
  push:
    branches:
      - main
      - master
jobs:
  imgcmp:
    runs-on: ubuntu-latest
    steps:
      - uses: 9sako6/imgcmp@v2.0.2
        with:
          token: ${{ secrets.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 }}
      - uses: 9sako6/imgcmp@v2.0.2
        id: imgcmp
        with:
          token: ${{ secrets.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 }}
      - name: Check outputs
        run: |
          echo ${{ steps.imgcmp.outputs.pull-request-number }}
